### PR TITLE
Fix no valid test when sharding

### LINKED ISSUE #267: No valid tests when using --shard and --changed-since
Hi, 

Say I've only made changed affecting one test, but have a CI with a 4 shard matrix. Then shard 2, 3 and 4 will get `Error: no valid tests found.` and the CI will fail. 

Could this be a warning instead of an error?

### PR DESCRIPTION
**Pull request by fellen31**
- Closes #267, by moving the `testSuits.isEmpty()` check so that shards with no tests do not result in an error.
- Clarifies the distinction between files with tests and the total number of tests within the files. E.g., so that one file containing with two tests aligns with the final `Executed 1 tests. 1 tests failed. Done!` message.
- Fixes a `java.lang.IllegalArgumentException: Input list cannot be null or empty` when running with a nonexistent tag (resulting in no tests) together with sharding.

### CODE REVIEW

**Comment by sateeshperi** [comment]
ah this makes sense now, saw this error just today and was perplexed about it.

Thanks for reporting and putting a fix @fellen31

**Comment by lukfor** [comment]
Thank you Felix! 🙏🚀

**Comment by nvnieuwk** [comment]
Any idea on when this will be in a release? :grin:

**Comment by lukfor** [comment]
Tomorrow 🙌

**Comment by lukfor** [comment]
Done 🚀

**Comment by nvnieuwk** [comment]
Awesome, thank you!

**Pull request merged**
